[package]
name = "hornet"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rand = "0.8.5"
serenity = "0.12.4"
tokio = {version = "1.42.0", features = ["macros", "rt-multi-thread"]}
